/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ca-central-1",
    "aws_cloud_logic_custom": [
        {
            "name": "server",
            "endpoint": "https://6pvpjdu5ue.execute-api.ca-central-1.amazonaws.com/dev",
            "region": "ca-central-1"
        }
    ],
    "aws_dynamodb_all_tables_region": "ca-central-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "mydatabase-dev",
            "region": "ca-central-1"
        },
        {
            "tableName": "pricedata-dev",
            "region": "ca-central-1"
        },
        {
            "tableName": "pricedata2-dev",
            "region": "ca-central-1"
        },
        {
            "tableName": "itemdb-dev",
            "region": "ca-central-1"
        }
    ],
    "aws_user_files_s3_bucket": "clientbc6cabec04d84d318144798d9000b9b3205313-dev",
    "aws_user_files_s3_bucket_region": "ca-central-1",
    "aws_cognito_identity_pool_id": "ca-central-1:85ca7a33-46b1-4827-ae75-694463376952",
    "aws_cognito_region": "ca-central-1",
    "aws_user_pools_id": "ca-central-1_PpgocuiOa",
    "aws_user_pools_web_client_id": "3e5qk8i1f53cp415ou2h26lpn9",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;
